name: flutter_customizable_calendar
description: a feature-rich Flutter package that offers highly customizable calendar views for displaying days, weeks, and months.
version: 0.3.0
homepage: https://github.com/Radency/flutter_customizable_calendar

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.11
  clock: ^1.1.1
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  intl: ^0.19.0
  collection: ^1.18.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.5
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
